swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      tags:
        - User Module
      summary: Accounts
      description: API for fetching accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: Accounts Fetched Successfully
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/{transactions}:
    get:
      tags:
        - User Module
      summary: Transactions
      description: API for fetching transactions of an account
      parameters:
        - in: path
          name: "accountId"
          description: The account id, as accountId
          required: true
          type : string
        - in: path
          name: "transactions"
          description: The transactions, as transactions
          required: true
          type : string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
        - in: body
          name: Account Id
          description: Id of account that needs to be fetched
          required: true
          schema:
            $ref: '#/definitions/AccountId'
      produces:
        - application/json
      responses:
        '200':
          description: Transactions Fetched Successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/{transactions}/{transactionId} :
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction API
      description: API for adding info to transaction
      parameters:
        - in: path
          name: "accountId"
          description: The account id, as accountId
          required: true
          type : string
        - in: path
          name: "transactions"
          description: The transactions, as transactions
          required: true
          type : string
        - in: path
          name: "transactionId"
          description: The transaction id, as transactionId
          required: true
          type : string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
        - in: body
          name: body
          description: Transaction info payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction info added successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction API
      description: API for deleting info in transaction
      parameters:
        - in: path
          name: "accountId"
          description: The account id, as accountId
          required: true
          type : string
        - in: path
          name: "transactions"
          description: The transactions, as transactions
          required: true
          type : string
        - in: path
          name: "transactionId"
          description: The transaction id, as transactionId
          required: true
          type : string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
        - in: body
          name: body
          description: Transaction info payload
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction info deleted successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Accounts:
    type: object
    properties:
      accounts :
        type : array
        items :
          type : object
          properties :
            accountId :
              type : string
            accountType :
              type : string
            balance :
              type : string
  AccountId :
    properties :
      accountId :
        type : string
  Transactions :
    type : array
    items :
      type : object
      properties :
        transactionNumber :
          type : string
        date :
          type : string
        description :
          type : string
        amount :
          type : string
        balance :
          type : string
        transactionType :
          type : string
        category :
          type : string
        notes :
          type : string
  Transaction :
    type : object
    properties :
      transactionNumber :
        type : string
      date :
        type : string
      description :
        type : string
      amount :
        type : string
      balance :
        type : string
      transactionType :
        type : string
      category :
        type : string
      notes :
        type : string